import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

class DocxGenerator:
    def __init__(self, report):
        self.report = report
        self.doc = Document()
        self.chart_dir = "chart_assets"

    def generate(self, output_path):
        self._add_cover()
        self._add_exec_summary()
        self._add_overview()
        self._add_financial()
        self._add_legal()
        self._add_conclusion()
        self.doc.save(output_path)

    def _add_cover(self):
        for _ in range(5): self.doc.add_paragraph()
        p = self.doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(self.report.organization.name or "Analysis Report")
        r.bold = True; r.font.size = Pt(28)
        p = self.doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run("NPO Intel Scout Report")
        r.font.size = Pt(14)
        p = self.doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run("Generated: " + datetime.now().strftime("%Y-%m-%d"))
        r.font.size = Pt(11)
        self.doc.add_page_break()

    def _add_exec_summary(self):
        self.doc.add_heading("1. Executive Summary", level=1)
        if self.report.conclusion_points:
            for pt in self.report.conclusion_points:
                self.doc.add_paragraph(pt, style="List Bullet")
        if self.report.critical_warnings:
            self.doc.add_heading("Warnings", level=2)
            for w in self.report.critical_warnings:
                self.doc.add_paragraph(w, style="List Bullet")

    def _add_overview(self):
        self.doc.add_heading("2. Organization Overview", level=1)
        if self.report.organization.founder:
            self.doc.add_paragraph("Founder: " + self.report.organization.founder)
        if self.report.governance:
            if self.report.governance.president:
                self.doc.add_paragraph("President: " + self.report.governance.president.name)

    def _add_financial(self):
        if not self.report.financial: return
        self.doc.add_heading("3. Financial Analysis", level=1)
        records = sorted(self.report.financial.records, key=lambda x: x.year)
        t = self.doc.add_table(rows=1+len(records), cols=3)
        for i, h in enumerate(["Year", "Total", "Change"]):
            c = t.rows[0].cells[i]; c.text = h
        prev = None
        for ri, rec in enumerate(records):
            c0 = t.rows[ri+1].cells[0]; c0.text = str(rec.year)
            c1 = t.rows[ri+1].cells[1]
            c1.text = "${:.1f}M".format(rec.total_expenditure or 0)
            c2 = t.rows[ri+1].cells[2]
            if prev and prev.total_expenditure and rec.total_expenditure:
                chg = (rec.total_expenditure - prev.total_expenditure) / prev.total_expenditure * 100
                c2.text = "{:+.1f}%".format(chg)
            prev = rec

    def _add_legal(self):
        if not self.report.legal: return
        self.doc.add_heading("4. Legal Assessment", level=1)
        for r in self.report.legal.records:
            self.doc.add_paragraph(f"- {r.jurisdiction}: {r.status} ({r.risk_level})")

    def _add_conclusion(self):
        self.doc.add_heading("5. Conclusion", level=1)
        self.doc.add_paragraph("Analysis generated by NPO Intel Scout v0.1")